# Generated by Django 5.1 on 2024-09-06 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_task_due_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='role',
        ),
    ]
