# Generated by Django 5.1 on 2024-09-09 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='confirmation_pin',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
