# Generated by Django 5.1 on 2024-09-11 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_customuser_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, default='avatar.jpg', null=True, upload_to='profiles/'),
        ),
    ]
