# Generated by Django 5.1 on 2024-09-11 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_customuser_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='image_profile',
            field=models.ImageField(blank=True, default='profiles/avatar.jpg', null=True, upload_to='profiles/'),
        ),
    ]
