# Generated by Django 5.1 on 2024-09-13 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_customuser_image_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='Boi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
