# Generated by Django 5.1 on 2024-09-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='icon',
            field=models.CharField(default='fa-list-alt', max_length=50),
        ),
    ]
