# Generated by Django 5.1 on 2024-09-25 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_todolist_icon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='description',
        ),
    ]
