# Generated by Django 5.1 on 2024-10-07 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0018_alter_activitylog_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitylog',
            name='user',
        ),
        migrations.AddField(
            model_name='activitylog',
            name='custom_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='base.customuser'),
            preserve_default=False,
        ),
    ]
