# Generated by Django 5.1 on 2024-10-07 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_remove_activitylog_custom_user_activitylog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
