# Generated by Django 5.1 on 2024-10-13 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_activitylog_update_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='task',
        ),
        migrations.AddField(
            model_name='comment',
            name='todo_list',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='base.todolist'),
            preserve_default=False,
        ),
    ]
